apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentdconf
  namespace: kube-system
data:
  fluent.conf: |
    <match fluent.**>
      @type null
    </match>
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    <match kubernetes.var.log.containers.**redis-app**.log>
      @type stdout
    </match>
    <match kubernetes.**>
      @type null
    </match>
